// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JW6vgh-o_2DfKnJCr4tfqXJlaCHZDgo',
    appId: '1:805426514266:web:be283a8cf15760932fcb63',
    messagingSenderId: '805426514266',
    projectId: 'quotegallery-app',
    authDomain: 'quotegallery-app.firebaseapp.com',
    storageBucket: 'quotegallery-app.firebasestorage.app',
    measurementId: 'G-BTR2HTHS17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHo9kQz4nHYL69wJ8T-lCtqBFmgb2JWNA',
    appId: '1:805426514266:android:c930c01fdcc2661f2fcb63',
    messagingSenderId: '805426514266',
    projectId: 'quotegallery-app',
    storageBucket: 'quotegallery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBxsPbK51sjDYP945SpalpvKTYUkjtol4',
    appId: '1:805426514266:ios:4ac48aebf27a24852fcb63',
    messagingSenderId: '805426514266',
    projectId: 'quotegallery-app',
    storageBucket: 'quotegallery-app.firebasestorage.app',
    iosBundleId: 'com.example.quoteGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBxsPbK51sjDYP945SpalpvKTYUkjtol4',
    appId: '1:805426514266:ios:4ac48aebf27a24852fcb63',
    messagingSenderId: '805426514266',
    projectId: 'quotegallery-app',
    storageBucket: 'quotegallery-app.firebasestorage.app',
    iosBundleId: 'com.example.quoteGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6JW6vgh-o_2DfKnJCr4tfqXJlaCHZDgo',
    appId: '1:805426514266:web:eb96c8b565cc38782fcb63',
    messagingSenderId: '805426514266',
    projectId: 'quotegallery-app',
    authDomain: 'quotegallery-app.firebaseapp.com',
    storageBucket: 'quotegallery-app.firebasestorage.app',
    measurementId: 'G-WWQKMFHW93',
  );

}